version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      # Save the node_modules cache
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build
      - run:
          name: Prettier and esLint
          command: npm run validate
      - run:
          name: storybook start
          command: npm run storybook
      - run:
          name: cypress test
          command: npm run test:browser:ci
      - run:
          name: test unit
          command: npm run test
workflows:
  version: 2
    build:
      jobs:
        - build
